/*
 * Copyright (c) 2022 bitlap
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema2.proto

package org.bitlap.tools.test.proto;

public final class DriverService {
  private DriverService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BOpenSession_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BOpenSession_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BOpenSession_BOpenSessionReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BOpenSession_BOpenSessionReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BOpenSession_BOpenSessionReq_ConfigurationEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BOpenSession_BOpenSessionReq_ConfigurationEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BOpenSession_BOpenSessionResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BOpenSession_BOpenSessionResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BOpenSession_BOpenSessionResp_ConfigurationEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BOpenSession_BOpenSessionResp_ConfigurationEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rschema2.proto\"\202\003\n\014BOpenSession\032\264\001\n\017BOp" +
      "enSessionReq\022\020\n\010username\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\022G\n\rconfiguration\030\003 \003(\01320.BOpenS" +
      "ession.BOpenSessionReq.ConfigurationEntr" +
      "y\0324\n\022ConfigurationEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\032\272\001\n\020BOpenSessionResp\022\016\n\006" +
      "status\030\001 \001(\t\022H\n\rconfiguration\030\002 \003(\01321.BO" +
      "penSession.BOpenSessionResp.Configuratio" +
      "nEntry\022\026\n\016session_handle\030\003 \001(\t\0324\n\022Config" +
      "urationEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B.\n\033org.bitlap.tools.test.protoB\rDri" +
      "verServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BOpenSession_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BOpenSession_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BOpenSession_descriptor,
        new String[] { });
    internal_static_BOpenSession_BOpenSessionReq_descriptor =
      internal_static_BOpenSession_descriptor.getNestedTypes().get(0);
    internal_static_BOpenSession_BOpenSessionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BOpenSession_BOpenSessionReq_descriptor,
        new String[] { "Username", "Password", "Configuration", });
    internal_static_BOpenSession_BOpenSessionReq_ConfigurationEntry_descriptor =
      internal_static_BOpenSession_BOpenSessionReq_descriptor.getNestedTypes().get(0);
    internal_static_BOpenSession_BOpenSessionReq_ConfigurationEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BOpenSession_BOpenSessionReq_ConfigurationEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_BOpenSession_BOpenSessionResp_descriptor =
      internal_static_BOpenSession_descriptor.getNestedTypes().get(1);
    internal_static_BOpenSession_BOpenSessionResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BOpenSession_BOpenSessionResp_descriptor,
        new String[] { "Status", "Configuration", "SessionHandle", });
    internal_static_BOpenSession_BOpenSessionResp_ConfigurationEntry_descriptor =
      internal_static_BOpenSession_BOpenSessionResp_descriptor.getNestedTypes().get(0);
    internal_static_BOpenSession_BOpenSessionResp_ConfigurationEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BOpenSession_BOpenSessionResp_ConfigurationEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
