addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.5.11")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.9.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.0.7")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.10.4")
